# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31644d87525b2ec3be3e729ed450f6e496c1f40f4df43d1a9692b0b603a9d7dadcecee4edbde1c15415d5642b90437dc8d001eda8ef37e81748269135bc17973

test:
  secret_key_base: e5b9c43fe5cdb7434f7608176135d5bd9c9fa21e6179dd662a95073156d39aaa7b3e6740661f4e4b7875d0d219d0b2585ef66481f25daeb561cde4d2175dc9b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
